    
    create table endereco (
       id int8 generated by default as identity,
        cep varchar(8) not null,
        bairro varchar(255) not null,
        cidade varchar(255) not null,
        estado varchar(255) not null,
        numero varchar(255) not null,
        rua varchar(255) not null,
        pessoa_id int8 not null,
        primary key (id)
    );
    
    create table pessoa (
       id int8 generated by default as identity,
        celular varchar(11) not null,
        cpf varchar(11) not null unique,
        data_nascimento date not null,
        email varchar(255) not null unique,
        nome varchar(255) not null,
        sexo varchar(9) not null,
        primary key (id)
    );
    
    alter table if exists endereco 
       add constraint fk_endereco_pessoa_id 
       foreign key (pessoa_id) 
       references pessoa;